server:
  port: "8080"

database:
  host: "postgres_db"
  port: "5432"
  user: "user"
  password: "password"
  dbname: "hospital_db"
  sslmode: "disable"

redis:
  addr: "redis_cache:6379"
  password: ""
  db: 0

jwt:
  secret: "your_super_secret_key"
