server:
  port: "8080"

database:
  host: "localhost"
  port: "5432"
  user: "user"
  password: "password"
  dbname: "hospital_db"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

jwt:
  secret: "your_super_secret_key"
