// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/forgot-password": {
            "post": {
                "description": "Sends a reset code to the user's phone",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Şifre sıfırlama kodu gönderir",
                "parameters": [
                    {
                        "description": "Forgot password info",
                        "name": "forgot",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ForgotPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "User login with email or phone, returns JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Kullanıcı girişi",
                "parameters": [
                    {
                        "description": "Login info",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Registers a hospital and its first authority",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Hastane ve ilk yetkili kaydı",
                "parameters": [
                    {
                        "description": "Register info",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthorityResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/reset-password": {
            "post": {
                "description": "Resets the user's password with the code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Şifreyi sıfırlar",
                "parameters": [
                    {
                        "description": "Reset password info",
                        "name": "reset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/cities": {
            "get": {
                "description": "Returns all cities (il)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location"
                ],
                "summary": "Tüm şehirleri listeler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CityLookup"
                            }
                        }
                    }
                }
            }
        },
        "/api/districts": {
            "get": {
                "description": "Returns all districts (ilçe) for a given city",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location"
                ],
                "summary": "Seçili ile ait ilçeleri listeler",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "City ID",
                        "name": "city_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.DistrictLookup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/personnel/job-groups": {
            "get": {
                "description": "Returns all job groups",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personnel"
                ],
                "summary": "Tüm meslek gruplarını listeler",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.JobGroupLookup"
                            }
                        }
                    }
                }
            }
        },
        "/api/personnel/staff": {
            "get": {
                "description": "Lists staff with filters and pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personnel"
                ],
                "summary": "Personelleri listeler (filtreli ve sayfalı)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "First name",
                        "name": "first_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Last name",
                        "name": "last_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "TC Kimlik No",
                        "name": "tc",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Job Group ID",
                        "name": "job_group_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Title ID",
                        "name": "title_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.StaffListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new staff member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personnel"
                ],
                "summary": "Personel ekler",
                "parameters": [
                    {
                        "description": "Staff info",
                        "name": "staff",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.StaffResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/personnel/staff/{id}": {
            "put": {
                "description": "Updates a staff member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personnel"
                ],
                "summary": "Personel günceller",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Staff ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Staff info",
                        "name": "staff",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.StaffResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a staff member",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personnel"
                ],
                "summary": "Personel siler",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Staff ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/personnel/titles": {
            "get": {
                "description": "Returns all titles for a given job group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Personnel"
                ],
                "summary": "Seçili meslek grubuna ait unvanları listeler",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job Group ID",
                        "name": "job_group_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.TitleLookup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/polyclinic/add": {
            "post": {
                "description": "Adds a polyclinic to the hospital",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polyclinic"
                ],
                "summary": "Hastaneye poliklinik ekler",
                "parameters": [
                    {
                        "description": "Polyclinic info",
                        "name": "polyclinic",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddHospitalPolyclinicRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.HospitalPolyclinicResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/polyclinic/all": {
            "get": {
                "description": "Returns all polyclinics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polyclinic"
                ],
                "summary": "Tüm poliklinikleri listeler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.PolyclinicLookup"
                            }
                        }
                    }
                }
            }
        },
        "/api/polyclinic/list": {
            "get": {
                "description": "Lists hospital's polyclinics with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polyclinic"
                ],
                "summary": "Hastanenin polikliniklerini listeler (sayfalı)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HospitalPolyclinicListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/polyclinic/remove/{id}": {
            "delete": {
                "description": "Removes a polyclinic from the hospital",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polyclinic"
                ],
                "summary": "Hastaneden poliklinik siler",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hospital Polyclinic ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/subuser": {
            "get": {
                "description": "Lists all subusers for the hospital",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SubUser"
                ],
                "summary": "Alt kullanıcıları listeler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.SubUserResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new subuser (yetkili/çalışan)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SubUser"
                ],
                "summary": "Alt kullanıcı ekler",
                "parameters": [
                    {
                        "description": "SubUser info",
                        "name": "subuser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSubUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SubUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/subuser/{id}": {
            "put": {
                "description": "Updates a subuser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SubUser"
                ],
                "summary": "Alt kullanıcıyı günceller",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SubUser ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SubUser info",
                        "name": "subuser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateSubUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SubUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a subuser",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SubUser"
                ],
                "summary": "Alt kullanıcıyı siler",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "SubUser ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddHospitalPolyclinicRequest": {
            "type": "object",
            "properties": {
                "polyclinic_id": {
                    "type": "integer"
                }
            }
        },
        "dto.AddStaffRequest": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "hospital_polyclinic_id": {
                    "type": "integer"
                },
                "job_group_id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "tc": {
                    "type": "string"
                },
                "title_id": {
                    "type": "integer"
                },
                "working_days": {
                    "type": "string"
                }
            }
        },
        "dto.AuthorityResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "hospital_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "tc": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.CityLookup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CreateSubUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "tc": {
                    "type": "string"
                }
            }
        },
        "dto.DistrictLookup": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.ForgotPasswordRequest": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.ForgotPasswordResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "dto.HospitalPolyclinicDetail": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "personnel_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PolyclinicPersonnelGroup"
                    }
                },
                "polyclinic_name": {
                    "type": "string"
                },
                "total_personnel": {
                    "type": "integer"
                }
            }
        },
        "dto.HospitalPolyclinicListResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "polyclinics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.HospitalPolyclinicDetail"
                    }
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.HospitalPolyclinicResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "polyclinic_id": {
                    "type": "integer"
                },
                "polyclinic_name": {
                    "type": "string"
                }
            }
        },
        "dto.JobGroupLookup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "properties": {
                "credential": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.PolyclinicLookup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.PolyclinicPersonnelGroup": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "group_name": {
                    "type": "string"
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "authority_email": {
                    "type": "string"
                },
                "authority_fname": {
                    "type": "string"
                },
                "authority_lname": {
                    "type": "string"
                },
                "authority_phone": {
                    "type": "string"
                },
                "authority_tc": {
                    "type": "string"
                },
                "city_id": {
                    "type": "integer"
                },
                "district_id": {
                    "type": "integer"
                },
                "hospital_email": {
                    "type": "string"
                },
                "hospital_name": {
                    "type": "string"
                },
                "hospital_phone": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "tax_number": {
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "repeat_new_password": {
                    "type": "string"
                }
            }
        },
        "dto.StaffListResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "staff": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StaffResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.StaffResponse": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "hospital_polyclinic_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "job_group_id": {
                    "type": "integer"
                },
                "job_group_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "polyclinic_name": {
                    "type": "string"
                },
                "tc": {
                    "type": "string"
                },
                "title_id": {
                    "type": "integer"
                },
                "title_name": {
                    "type": "string"
                },
                "working_days": {
                    "type": "string"
                }
            }
        },
        "dto.SubUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "tc": {
                    "type": "string"
                }
            }
        },
        "dto.TitleLookup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateStaffRequest": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "hospital_polyclinic_id": {
                    "type": "integer"
                },
                "job_group_id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "tc": {
                    "type": "string"
                },
                "title_id": {
                    "type": "integer"
                },
                "working_days": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateSubUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "description": "\"yetkili\" veya \"calisan\"",
                    "type": "string"
                },
                "tc": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
